### ISSUE TITLE
Can't read input field in 2.0

### ISSUE THREAD

**Issue by paul1149** [TobiasBielefeld/Simple-Search#27]
I just updated the 2.0 today, and found that the input field is a dark gray and the text of it is just slightly lighter, virtually imperceptible. This is true whether the theme is light, dark, or follow the system. The rest of the interface is dark the way I would expect when I'm following the phones theme. I'm on Android 10 on a Motorola G7. Thanks for this app I really do appreciate it.

**Comment by TobiasBielefeld** [comment]
Hi, did you try version 2.0.1 yet? It changed a bit on the theming. I can sadly not reproduce the problem on my Android 10 Emulator. The background color of the input field is explicitly set to white (#ffffff) so I am not sure how this could change.

**Comment by TobiasBielefeld** [comment]
Oh sorry, I found the code part that set the background color... this will be removed in the next version

**Comment by paul1149** [comment]
GREAT. Thanks much!

**Comment by paul1149** [comment]
Just installed the update, and it's working beautifully. I have dark text on a white, or light, background. It's not following my dark system theme, but that's inconsequential. Thanks so much for your attention to this problem. I'm going to close this issue. Be well.
