### ISSUE TITLE
[Feature] Add dark theme

### ISSUE THREAD

**Issue by TobiasBielefeld** [TobiasBielefeld/Simple-Search#8]
Some people sent me e-mails asking for a dark theme

**Comment by TobiasBielefeld** [comment]
- also add a dark themed widget

**Comment by LeksN** [comment]
The dark theme would not be bad, but it would also look cool transparent theme, it is more universal, suitable for any design.

**Comment by TobiasBielefeld** [comment]
I'll see how good a transparent theme works out

**Comment by TobiasBielefeld** [comment]
dark theme added in version 1.2
